### ISSUE TITLE
Errot on  installtion

### ISSUE THREAD

**Issue by artydev** [sadhbh-c0d3/pydotnet#11]
In fact, I got the same error with Python 3.12...

You can close it, wrong Python version.
My bad

Regards

Hello,

I got an error when installing pydotnet.
Can you help me please ?

Regards

![image](https://github.com/sadhbh-c0d3/pydotnet/assets/31207473/50e4828e-441f-45a3-90b1-593a033524de)

**Comment by sadhbh-c0d3** [comment]
The name of the module you need to install is `dotnet` and not ~`pydotnet`~ so you need to do `pip install dotnet`
